### ISSUE TITLE
'Extra' option

### ISSUE THREAD

**Issue by God-damnit-all** [patrickenfuego/FFEncoder#2]
For using ffmpeg parameters that aren't covered by the PowerShell function, it would be nice to have an '-Extra' parameter that forwards a hash table of parameters and arguments to the called ffmpeg process.

**Comment by patrickenfuego** [comment]
Hey ImportTaste! Thanks for the feedback. I've been planning to implement a feature just as you described for some time now, but unfortunately, it keeps slipping my mind. I will see if I can work on it this week.

**Comment by patrickenfuego** [comment]
@ImportTaste 

Two additional parameters have been added, ```-x265Extra``` and ```-FFMpegExtra```, that allow you to pass additional values to ffmpeg and x265. I've updated the README and help info with instructions on how to use them.
