### ISSUE TITLE
[FR] AV1 & x264

### ISSUE THREAD

**Issue by God-damnit-all** [patrickenfuego/FFEncoder#5]
This is such a good wrapper for ffmpeg that it is a shame to limit it to only x265. While it is my encoder of choice, I still need x264 for videos I want to be playable on Discord. And then there's AV1, which is browser-compatible (except for electron, for now) and is already better than x265 in terms of compression rate (compression speed not so much).

I'd really like to see it expanded.

**Comment by patrickenfuego** [comment]
Hey @ImportTaste funny you should say, I've already begun integrating x264 support. It's been backlogged by a few other projects, but should be completed soon.

As for AV1, not sure when I'll get around to that. I don't use it much, but I'll make a point to look at it soon.

**Comment by God-damnit-all** [comment]
is the x264-dev branch ready for testing, or is it still in the preliminary phase?

**Comment by patrickenfuego** [comment]
It took me a century (sorry, very busy), but it's finally done. While I didn't add AV1, I did add a *ton* of new features in the latest release. Hope you enjoy it.

**Comment by ImportTaste** [comment]
Thanks!

**Comment by God-damnit-all** [comment]
Amazing work! Thanks.
